# Generated by Django 3.0.4 on 2020-03-10 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='Zip code has to be 6 characters', regex='^.{5,6}')])),
            ],
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnticoagulationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_inr', models.FloatField()),
                ('treatment_start_date', models.DateField()),
                ('reason_for_treatment', models.TextField()),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticoagulation_monitoring.Anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255)),
                ('iupac_name', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugDosageSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('sunday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='anticoagulation_monitoring.Address')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPractitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticoagulation_monitoring.Address')),
                ('employed_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anticoagulation_monitoring.Facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticoagulation_monitoring.Address')),
                ('general_practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anticoagulation_monitoring.GeneralPractitioner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticoagulation_monitoring.Address')),
                ('employed_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anticoagulation_monitoring.Facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugDosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(verbose_name='strength in miligrams')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticoagulation_monitoring.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='AnticoagulationRecordEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inr_measured', models.FloatField()),
                ('AnticoagulationRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticoagulation_monitoring.AnticoagulationRecord')),
                ('drug_dosage_schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='anticoagulation_monitoring.DrugDosageSchedule')),
            ],
        ),
        migrations.AddField(
            model_name='anticoagulationrecord',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticoagulation_monitoring.Drug'),
        ),
        migrations.AddField(
            model_name='anticoagulationrecord',
            name='treatment_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticoagulation_monitoring.Facility'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anticoagulation_monitoring.Patient'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticoagulation_monitoring.Country'),
        ),
    ]
